apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-worker-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: tradingsystem-worker-deployment
  minReplicaCount: 2
  maxReplicaCount: 15
  triggers:
  - type: rabbitmq
    metadata:
      queueName: fetch-stock-price-queue
      host: amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672/
      mode: QueueLength
      value: "50"
