USE tradingsystem;

ALTER TABLE TradeOrders
    ADD COLUMN IF NOT EXISTS ExecutedVolume DECIMAL(18, 4) NOT NULL DEFAULT 0;

ALTER TABLE TradeOrders
    ADD COLUMN IF NOT EXISTS QueuedVolume DECIMAL(18, 4) NOT NULL DEFAULT 0;

ALTER TABLE TradeOrders
    ADD COLUMN IF NOT EXISTS Status VARCHAR(50) NOT NULL DEFAULT 'Pending';

ALTER TABLE TradeOrders
    ADD COLUMN IF NOT EXISTS CreatedAt TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE TradeOrders
    ADD COLUMN IF NOT EXISTS ProcessedAt TIMESTAMP(6) NULL;

ALTER TABLE StockPrices
    ADD COLUMN IF NOT EXISTS AvailableVolume DECIMAL(18, 4) NOT NULL DEFAULT 0;

ALTER TABLE StockPrices
    ADD COLUMN IF NOT EXISTS PendingBuyVolume DECIMAL(18, 4) NOT NULL DEFAULT 0;

ALTER TABLE StockPrices
    ADD COLUMN IF NOT EXISTS PendingSellVolume DECIMAL(18, 4) NOT NULL DEFAULT 0;

UPDATE StockPrices
SET AvailableVolume = TotalStockVolume
WHERE AvailableVolume = 0;
