apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradingsystem-rabbitmq
  namespace: trading-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradingsystem-rabbitmq
  template:
    metadata:
      labels:
        app: tradingsystem-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.2-management-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: trading-system-secrets
                  key: rabbitmq-password
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tradingsystem-rabbitmq
  namespace: trading-system
spec:
  selector:
    app: tradingsystem-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
