apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradingsystem-cache
  namespace: trading-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradingsystem-cache
  template:
    metadata:
      labels:
        app: tradingsystem-cache
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:9.0-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tradingsystem-cache
  namespace: trading-system
spec:
  selector:
    app: tradingsystem-cache
  ports:
    - port: 6379
      targetPort: 6379
